dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: wSvphxZ4vmxR51WJ4L0WjZUMF4lUjLNuGeiRqrbQosrzcjS5E32euLtgH2+j1WvBPJnzb+o5J3wz++RxDJRhzM8R/Ipn1ooNDNNEiBrTRUeMW/UZFCv0EzBT0yfIatULPo+Cye0Fe2KCs9bSYidrwvBhfqEoS1Va2YwR5m+DkKli9G1fb2VzPfZuHvc7KjjLYWJQcFw/w2306eWVWFqHLgnkI6oxY+bmKZsbVihwxwYPTonFk9sdfzYlDKL0ld3y8k69c+4rEPup1yvD1xcECsHKTaTxPB97BtX5U4do9m2G3OabPoTFucxJAa8ziRZMjsR6t6/tQoQjbvxhHXGJFN6vHs4gQBZKuJiSuvQqSH0QQLvkJV+jj9FfIemtEnwRJYwWSTpXewQ1V5yI3fwvhwfVpqTcp6LQHfp9e/Qx/TUNqJY0y85CUKkr28jNNU55YOvOKnBJ+BqY8DLipiiyz6KtW4oRnmBVlOKnLoZQdJDjzGSm766Out6pDLwe17RG0r2IPU1QiMGilqaD69GfL2h9H/wOymx8v80kfnz1jHVMaWM4kKqWudH3E2DAMyoam76YWCTL16lsbQBGbG26zbF18wSkCYsVI9BbBF2NVn/BkbIVVxzKS4lHVvss2xlwInrZDFC5DhVxLacD8T/p25+Qgk/eexL/sJJAsJsGoQI=
  file: Gerbers/PIN-103_gerbers.zip
  on:
    repo: w4xzr/PIN-103
  skip_cleanup: 'true'
